### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by mrlonely001** [jojolin/Owesome-programming-tools#1]
感谢大神当年的无私经验传授，除了tmux ， 其他都get到了

**Comment by jojolin** [comment]
really? 请问vim如何将所有的tab替换成四个的空格

**Comment by jojolin** [comment]
> 感谢大神当年的无私经验传授，除了tmux ， 其他都get到了

really? 请问vim如何将所有的tab替换成四个的空格
